# See https://pre-commit.com for more information
# See https://pre-commit.ci for more information
ci:
  # I don't need so many duplicated notifications on the same thing as I keep
  # autoupdating manually too. Besides it just creates extra branch I never
  # touch.
  # https://github.com/pre-commit-ci/issues/issues/83
  autoupdate_schedule: quarterly

default_language_version:
  python: pypy3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude_types: [markdown]

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args: [--update-only, --notitle]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-gitlab-ci

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies: [
            # https://www.npmjs.com/package/prettier
            "prettier@3.0.3",
            # https://www.npmjs.com/package/@prettier/plugin-xml
            "@prettier/plugin-xml@3.2.0",
          ]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.2"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args: [-disable-max-line-length]
