# Site settings
title: Mikaela's supybot site
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mikaela's Supybot site where nowadays the only content is security issues
  of stock Supybot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://supybot.mikaela.info/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Mikaela

# Build settings
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript"]

# Custom settings
timezone: Etc/UTC
encoding: utf-8
gems:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
sitemap:
    file: "/sitemap.xml"
