# Site settings
theme: minima
title: Mikaela's supybot site
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mikaela's Supybot site where nowadays the only content is security issues
  of stock Supybot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://supybot.mikaela.info/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: Mikaela

# Custom settings
lang: en
timezone: Etc/UTC
encoding: utf-8
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
sitemap:
  file: "/sitemap.xml"
include: [robots.txt]
